version: '3.5'

services:
  db_todo:
    container_name: db_todo
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1
      - POSTGRES_USER=postgres
    image: postgres:14.3-alpine